type TformDataInputs = {
  [key: string]: {
    title: string;
    inputType: string;
    selectOptions: string[];
  };
};

export const formDataInputs: TformDataInputs = {
  asansor_adi: { title: "Asansör Adı", inputType: "text", selectOptions: [] },
  kapasite_kg: {
    title: "Kapasite (ağırlık)",
    inputType: "select",
    selectOptions: ["“”", "400", "535", "625", "675", "800", "1000", "1050", "1125", "1275", "1600", "1800", "2000"],
  },
  kapasite_kisi: {
    title: "Kapasite (insan sayısı)",
    inputType: "select",
    selectOptions: [
      "“”",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
    ],
  },
  hiz: {
    title: "Hız",
    inputType: "select",
    selectOptions: ["“”", "0,15", "0,30", "1.0", "1.6", "1.75", "2.0", "2.5", "3.0"],
  },
  makine_dairesi: {
    title: "Makine Dairesi",
    inputType: "select",
    selectOptions: ["MRL", "MR"],
  },
  motor_gucu: { title: "Motor Gücü", inputType: "text", selectOptions: [] },
  kontrol_sistemi: {
    title: "Kontrol Sistemi",
    inputType: "select",
    selectOptions: [
      "“”",
      "1KS (Aşağı-Yukarı Yön Toplamalı) Asansör, girilen tüm kabin ve kat çağrılarını kaydeder. Asansör yukarı doğru hareket ederken yukarı çağrıları alır. Aşağı doğru hareket ederken aşağı çağrıları alır. Seyahat yönü, kayıtlı tüm kabin ve çağrıları sonlanıncaya kadar sürdürülür",
      "2KS (Dublex - Aşağı-Yukarı Yön Toplamalı) Asansör, girilen tüm kabin ve kat çağrılarını kaydeder. Asansör yukarı doğru hareket ederken yukarı çağrıları alır. Aşağı doğru hareket ederken aşağı çağrıları alır. Seyahat yönü, kayıtlı tüm kabin ve çağrıları sonlanıncaya kadar sürdürülür",
      "PORT  ",
    ],
  },
  saate_trip_sayisi: {
    title: "Saate Trip Sayısı",
    inputType: "select",
    selectOptions: ["“”", "180", "240"],
  },
  durak_sayisi: {
    title: "Durak Sayısı",
    inputType: "select",
    selectOptions: [
      "“”",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "41",
      "42",
      "43",
      "44",
      "45",
      "46",
      "47",
      "48",
      "49",
      "50",
    ],
  },
  first_floor: {
    title: "Başlangıç Katı",
    inputType: "select",
    selectOptions: ["0", "-1", "-2"],
  },
  kapi_sayisi: {
    title: "Kapı Sayısı",
    inputType: "select",
    selectOptions: [
      "“”",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
      "32",
      "33",
      "34",
      "35",
      "36",
      "37",
      "38",
      "39",
      "40",
      "41",
      "42",
      "43",
      "44",
      "45",
      "46",
      "47",
      "48",
      "49",
      "50",
    ],
  },
  high_floor: { title: "Yüksek Kat", inputType: "select", selectOptions: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"] },
  giris_yonu: { title: "Giriş Yönü", inputType: "select", selectOptions: ["“”", "1", "2"] },
  seyir_mesafesi: { title: "Seyir Mesafesi (m)", inputType: "text", selectOptions: [] },
  saft_olculeri_w: { title: "Şaft Ölçüsü W (mm)", inputType: "text", selectOptions: [] },
  saft_olculeri_d: { title: "Şaft Ölçüsü D (mm)", inputType: "text", selectOptions: [] },
  son_kat_mesafesi: { title: "Son Kat Mesafesi (mm)", inputType: "text", selectOptions: [] },
  kuyu_derinligi: { title: "Kuyu Derinliği (mm)", inputType: "text", selectOptions: [] },
  kabin_w: { title: "Kabin Ölçüsü W (mm)", inputType: "text", selectOptions: [] },
  kabin_d: { title: "Kabin Ölçüsü D (mm)", inputType: "text", selectOptions: [] },
  kabin_h: { title: "Kabin Ölçüsü H (mm)", inputType: "text", selectOptions: [] },
  kapi_wd: {
    title: "Kapı Ölçüsü WD (mm)",
    inputType: "select",
    selectOptions: ["“”", "750", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500"],
  },
  kapi_hd: { title: "Kapı Ölçüsü HD (mm)", inputType: "select", selectOptions: ["“”", "2000", "2100", "2200", "2300"] },
  kapi_tipi: {
    title: "Kapı Tipi",
    inputType: "select",
    selectOptions: [
      "“”",
      "Tam Otomatik Merkezi Açılır Kapı C2",
      "Tam Otomatik Merkezi Teleskopik Açılır Kapı C4",
      "Tam Otomatik Merkezi Teleskopik Açılır Kapı C6",
      "Tam Otomatik Teleskopik Açılır Kapı – T2",
      "Tam Otomatik Teleskopik Açılır Kapı – T3",
      "Tam Otomatik Teleskopik Açılır Kapı – T4",
    ],
  },
  saft_konstruksiyonu: {
    title: "Şaft Konstrüksiyonu",
    inputType: "select",
    selectOptions: ["“”", "Betonarme", "Çelik"],
  },
  kabin_dizayni: {
    title: "Kabin Dizaynı",
    inputType: "select",
    selectOptions: ["“”", "Boş Kabin", "NAVONA", "TIMES SQUARE", "PARK AVENUE", "SUNSET BOULEVARD"],
  },
  kabin_yan_duvar: {
    title: "Kabin Yan Duvarları",
    inputType: "select",
    selectOptions: [
      "“”",
      "San Marino Blue\tBoyalı",
      "Genoa Green\tStainless Steel",
      "Capri Yellow",
      "Riga Grey",
      "Oxford Green",
      "Polar White",
      "Siena Brown",
      "Mascara Red",
      "Capri Lemon",
      "Ravenna Orange",
      "Catania Light Grey",
      "Cadiz Blue",
      "Suez Grey",
      "Athens Grey",
      "Granada Metallic Platinum",
      "Maribor Metallic Silver",
      "Kashmir Blue",
      "Oxford Blue",
      "Toronto Titanium",
      "Petersburg Amber",
      "Birmingham Anthracite",
      "Stockholm Grey",
      "Leon Silver",
      "Santorini White",
      "Arosa Wood",
      "Chicago Wood",
      "Slavonia Wood",
      "Vancouver Wood",
      "Stainless Steel Hairline",
      "Stainless Steel Polished Mirror",
    ],
  },
  kabin_arka_duvar: {
    title: "Kabin Arka Duvarı",
    inputType: "select",
    selectOptions: [
      "“”",
      "San Marino Blue\tBoyalı",
      "Genoa Green\tStainless Steel",
      "Capri Yellow",
      "Riga Grey",
      "Oxford Green",
      "Polar White",
      "Siena Brown",
      "Mascara Red",
      "Capri Lemon",
      "Ravenna Orange",
      "Catania Light Grey",
      "Cadiz Blue",
      "Suez Grey",
      "Athens Grey",
      "Granada Metallic Platinum",
      "Maribor Metallic Silver",
      "Kashmir Blue",
      "Oxford Blue",
      "Toronto Titanium",
      "Petersburg Amber",
      "Birmingham Anthracite",
      "Stockholm Grey",
      "Leon Silver",
      "Santorini White",
      "Arosa Wood",
      "Chicago Wood",
      "Slavonia Wood",
      "Vancouver Wood",
      "Stainless Steel Hairline",
      "Stainless Steel Polished Mirror",
    ],
  },
  kabin_kapisi: { title: "Kabin Kapısı", inputType: "select", selectOptions: ["“”", "Boyalı", "Stainless Steel"] },
  kabin_zemin_tipi: {
    title: "Kabin Zemin Tipi",
    inputType: "select",
    selectOptions: ["“”", "Boş", "Artificial Granite", "Rubber"],
  },
  kabin_zemin_rengi: {
    title: "Kabin Zemin Rengi",
    inputType: "select",
    selectOptions: ["“”", "Black", "Grey", "Sand", "Brown", "Light Grey", "Dark Grey"],
  },
  kabin_tavani: {
    title: "Kabin Tavanı",
    inputType: "select",
    selectOptions: ["“”", "Boş", "Boyalı", "Stainless Steel"],
  },
  kabin_aydinlatmasi: {
    title: "Kabin Aydınlatması",
    inputType: "select",
    selectOptions: ["“”", "Line", "Round Spots", "Curve", "Square Spots", "Bracket", "Indirect", "Dash", "Surround"],
  },
  kabin_butonu: {
    title: "Kabin Butonu (COP)",
    inputType: "select",
    selectOptions: [
      "“”",
      "Linea 100 Mekanik  buton Kabin pozisyon göstergesi, çağrıların görsel ve optik  konformasyonu, kapı açma kapama butonları, alarm butonu, aşırı yük göstergesi",
      "Linea 120 Dokunmatik  buton Kabin pozisyon göstergesi, çağrıların görsel ve optik  konformasyonu, kapı açma kapama butonları, alarm butonu, aşırı yük göstergesi",
    ],
  },
  kabin_butonu_konumu: {
    title: "Kabin Butonu Konumu",
    inputType: "select",
    selectOptions: ["“”", "Yan Duvarda", "Ön Duvarda"],
  },
  kabin_kupestesi: {
    title: "Kabin Küpeştesi",
    inputType: "select",
    selectOptions: ["“”", "Boyalı", "Stainless Steel"],
  },
  kabin_aynasi: {
    title: "Kabin Aynası",
    inputType: "select",
    selectOptions: ["“”", "500 x 2100 mm Tam boy  - Arka duvarda", "500 x 2100 mm Tam boy  - Yan duvarda", "500 x 1200 mm Yarım boy  - Arka duvarda"],
  },
  kat_kapisi: { title: "Kat Kapısı", inputType: "select", selectOptions: ["“”", "Boyalı", "Stainless Steel"] },
  kat_butonu: {
    title: "Kat Butonu (LOP)",
    inputType: "select",
    selectOptions: [
      "“”",
      "Mekanik buton bütün katlarda kabin pozisyon göstergesi, kabin yön göstergesi",
      "Dokunmatik buton bütün katlarda kabin pozisyon göstergesi, kabin yön göstergesi",
    ],
  },
  kat_butonu_konumu: {
    title: "Kat Butonu Konumu",
    inputType: "select",
    selectOptions: ["“”", "Kat kapı duvarında ankastre gömme", "Kat kapı duvarında Sıva üstü", "Kat kapı kasasında ankastre gömme"],
  },
  adet_fiyati: { title: "Adet Fiyatı", inputType: "text", selectOptions: [] },
  adet: { title: "Adet", inputType: "text", selectOptions: [] },
  toplam_fiyat: { title: "Toplam Fiyat", inputType: "text_read_only", selectOptions: [] }, // auto
  toplam_fiyatW: { title: "Toplam Fiyat", inputType: "text_read_only", selectOptions: [] }, // auto
};
