name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21.4"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          export CI=false
          yarn build

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          firebase deploy --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
